name: ft_containers
on: push
jobs:
  run_application_mac:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - run: make
      - run: make -C unit_tests
      - run: ./unit_tests/test
