name: ft_containers
on:
    push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run_application_mac:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - run: make
      - run: clang++ -Wall -Wextra -Werror -std=c++98 test.cpp
